### ISSUE TITLE
Error retrieving "public link of the file"

### ISSUE THREAD

**Issue by ratzat** [CornHusker89/lc-mod-downloader#1]
File is open to anyone with link.
Code works first time running until [x753-More_Suits-1.4.1] where it will either fail to download PNG skin files or mod icon.
After first time, error occurs after retrieving and processing all mod folders, which it (should) have access to. (gdown.exceptions)

Full error after running third time with extra mods:
An error occured:
Traceback (most recent call last):
  File "gdown\download.py", line 232, in download
  File "gdown\download.py", line 49, in get_url_from_gdrive_confirmation
gdown.exceptions.FileURLRetrievalError: Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 68, in <module>
  File "gdown\download_folder.py", line 293, in download_folder
  File "gdown\download.py", line 243, in download
gdown.exceptions.FileURLRetrievalError: Failed to retrieve file url:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

        https://drive.google.com/uc?id=1O1me05jd3aczRXUmjZtyaUxWYQj-SZwn

but Gdown can't. Please check connections and permissions.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 70, in <module>
Exception: An error occured while downloading a folder with link https://drive.google.com/drive/folders/1262-goPA8VV0UDXHIeP8H9r6XFhaXziH (make sure this is a valid and publicly accessable link). Error: Traceback (most recent call last):
  File "gdown\download.py", line 232, in download
  File "gdown\download.py", line 49, in get_url_from_gdrive_confirmation
gdown.exceptions.FileURLRetrievalError: Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 68, in <module>
  File "gdown\download_folder.py", line 293, in download_folder
  File "gdown\download.py", line 243, in download
gdown.exceptions.FileURLRetrievalError: Failed to retrieve file url:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

        https://drive.google.com/uc?id=1O1me05jd3aczRXUmjZtyaUxWYQj-SZwn

but Gdown can't. Please check connections and permissions.

**Comment by CornHusker89** [comment]
seems to be fixed, can be reopened if need be
